### PR TITLE
Ensure node-gyp is executable

### LINKED ISSUE #20: Problem with npm dependency resolution
There seems to be an issue when attempting to resolve npm modules declared in `package.json` when they depend upon the `node-gyp` package. Steps to reproduce:

- add JSDOM as a dependency in the `sbt-js-engine-tester` project:

```
{
    "name": "somename",
    "version": "1.0.0",
    "dependencies": {
        "console-browserify": "0.1.6",
        "jsdom": "1.0.3"
    }
}
```

- attempt to run npm module resolution:

```
sbt web-assets:jseNpmNodeModules
```

when that one package gets installed by hand previously (`npm install node-gyp`) the command runs without a hitch.

### PR DESCRIPTION
**Pull request by jroper**
Fixes #20

### CODE REVIEW

**Comment by benmccann** [comment]
@jroper probably good to change from sbt 0.13.5-RC3 to 0.13.5 throughout the scripted tests. I sent a PR for that here: https://github.com/sbt/sbt-js-engine/pull/36

also, I think there may be cleaner ways of fixing this problem. see my comment in https://github.com/sbt/sbt-js-engine/issues/20#issuecomment-110056004

thanks again for tracking this down! it was quite frustrating

**Comment by huntc** [comment]
I think we should avoid encoding support for specific libraries. That will start an ugly precedent. I don't have another idea just yet, but let's not do this...

**Comment by huntc** [comment]
How about making everything under the npmDir / "bin" folder executable by convention?

**Comment by huntc** [comment]
Also, I'm wondering if this can be taken care of with our npm project itself...

**Comment by jroper** [comment]
Well, this code *is* very specific about npm, a few lines later it invokes a specific script in the npm webjar.

And the root problem is that there is no standard way to carry file execute permissions in a zip file, so the ant zip implementation which unzips nom in the webjar build loses it, and the JDK implementation which maven uses to zip the webjar in the webjar build loses it, and the JDK implementation which the webjar extractor uses to unzip the webjar loses it. So the proper fix is to fix ant, maven and webjars extractor to support a non standard zip extension, and only then can we produce and consume an npm webjar that keeps the execute permission. But that would also be a very fragile solution, because of one of those components in the chain is ever replaced by something that doesn't support the non standard zip extension, then it will break again.

**Comment by huntc** [comment]
OK, so how about this though:

> How about making everything under the npmDir / "bin" folder executable by convention?

**Comment by benmccann** [comment]
It seems like a lot of extra work for little benefit to take things that are in npm and repackage them into jars such that we lose all the file permissions in the process. Can't we just grab directly from npm instead?

This would work much better:

    wget http://registry.npmjs.org/npm/-/npm-2.11.1.tgz
    tar -zxvf npm-2.11.1.tgz

**Comment by jroper** [comment]
Directly using npm negates all the advantages of a package management system.  It would mean Activator offline distribution would need to be distributed both with an ivy cache and an npm cache, as well as npm itself.  You'd lose all the advantages of caching because at best you could only cache the npm download for a project.  It would mean if you wouldn't be able to take advantage of nexus proxies, and you'd have to double configure http proxies, once for ivy and once for npm.

**Comment by jroper** [comment]
@huntc Making everything in bin executable is as much of a hack as this is - potentially a worse hack, you don't want to give arbitrary files that should not be executed execute permission.

Let me just point out, the line of code immediately after what this PR doesn't show is this:

```scala
val npm = new Npm(engine, (webJarsNodeModulesDirectory in Plugin).value / "npm" / "lib" / "npm.js")
```

So, we're already asserting that a particular file has to exist in a particular location within the npm webjar, so this code is already very specific to the internals of npm, I don't see the hack here as an issue of generalisation since this code has a requirement to be specialised already, so the fact that this is just specific to npm is not why I think it's a hack.  In my eyes, the hack is the location at which this file is made executable, the non hacky, but impractical solution is making the execute permission come from the webjar itself.

**Comment by huntc** [comment]
The npm.js file is a part of the npm ecosystem.

**Comment by huntc** [comment]
Perhaps a compromise here is to have a setting that declares which files should receive the executable permission.

**Comment by jroper** [comment]
The node-gyp file is also part of the npm ecosystem, it's a facility that npm makes available to allow libraries to compile native code against the instance of node provided by the platform.

I'll look at adding something to webjars to declare file permissions.

**Comment by huntc** [comment]
OK, I didn't realise that node-gyp was part of the ecosystem - apologies for the disconnect. All good then.

**Comment by jroper** [comment]
PR here:

https://github.com/webjars/webjars-locator-core/pull/3

**Comment by huntc** [comment]
So I take it then that this pr is no longer required?

**Comment by benmccann** [comment]
@jroper I'm going to close this since it sounds like it was fixed in webjars-locator-core instead

**Pull request closed without merging**
