### PR TITLE
Fix severity read issue #22.

### LINKED ISSUE #22: Problem severity is not correctly parsed.
Plugins depending on sbt-js-engine cannot report severity other than `"error"` because the match is done on "strings with quotes" (see https://github.com/sbt/sbt-js-engine/blob/master/src/main/scala/com/typesafe/sbt/jse/SbtJsTask.scala#L112). For example, a plugin reporting `severity: "warn"` would match `case "\"warn\"" =>` in the linked match statement, but not `case "warn" =>` since `v.toString()` yields `"warn"`.

### PR DESCRIPTION
**Pull request by niladic**
Test and fix #22. I added scalacheck as a test dependency, I hope this is ok.

### CODE REVIEW

**Comment by jroper** [comment]
Hi @niladic,

Thankyou for your contribution.  Would you mind signing our CLA?

http://www.typesafe.com/contribute/cla

Thanks!

**Comment by benmccann** [comment]
@niladic just a reminder to sign the CLA. you did so much work on this PR it'd be a shame not to get it through the finish line

**Comment by niladic** [comment]
I am very sorry for not answering sooner. I signed the CLA. Do you need me to rebase against master ?

**Comment by benmccann** [comment]
yes, please

**Comment by niladic** [comment]
Ok, it's done.

**Pull request merged**
